apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    app.kubernetes.io/managed-by: bicep
  name: hello
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    app.kubernetes.io/managed-by: bicep
  name: hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        app.kubernetes.io/managed-by: bicep
    spec:
      containers:
        - image: nginx:alpine
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          name: hello
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
