// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: extension.proto

// This contract is based on the following extension contract for server-side extensibility:
// https://github.com/Azure/bicep-extensibility/blob/main/docs/vnext/openapi.yaml

package extension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type ResourceSpecification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains configuration items that are served as necessary context information for completing the resource operation.
	// This is the user-supplied extension configuration in the Bicep or ARM template file.
	// Formatted as a serialized JSON string.
	Config *string `protobuf:"bytes,1,opt,name=config,proto3,oneof" json:"config,omitempty"`
	// The type of the resource.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The API version of the resource.
	ApiVersion *string `protobuf:"bytes,3,opt,name=apiVersion,proto3,oneof" json:"apiVersion,omitempty"`
	// The properties of the resource.
	// Formatted as a serialized JSON string.
	Properties    string `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpecification) Reset() {
	*x = ResourceSpecification{}
	mi := &file_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpecification) ProtoMessage() {}

func (x *ResourceSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpecification.ProtoReflect.Descriptor instead.
func (*ResourceSpecification) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceSpecification) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

func (x *ResourceSpecification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceSpecification) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

func (x *ResourceSpecification) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

type ResourceReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An object comprising key properties that, when paired with the resource's type and configuration, uniquely identify a resource.
	// These properties are generally a subset of the resource properties provided in the createOrUpdate request payload.
	// Formatted as a serialized JSON string.
	Identifiers string `protobuf:"bytes,1,opt,name=identifiers,proto3" json:"identifiers,omitempty"`
	// Contains configuration items that are served as necessary context information for completing the resource operation.
	// This is the user-supplied extension configuration in the Bicep or ARM template file.
	// Formatted as a serialized JSON string.
	Config *string `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	// The type of the resource.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// The API version of the resource.
	ApiVersion    *string `protobuf:"bytes,4,opt,name=apiVersion,proto3,oneof" json:"apiVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReference) Reset() {
	*x = ResourceReference{}
	mi := &file_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReference) ProtoMessage() {}

func (x *ResourceReference) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReference.ProtoReflect.Descriptor instead.
func (*ResourceReference) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceReference) GetIdentifiers() string {
	if x != nil {
		return x.Identifiers
	}
	return ""
}

func (x *ResourceReference) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

func (x *ResourceReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceReference) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

type LocalExtensibilityOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource data if the operation succeeded.
	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	// Error information if the operation failed.
	ErrorData     *ErrorData `protobuf:"bytes,2,opt,name=errorData,proto3,oneof" json:"errorData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalExtensibilityOperationResponse) Reset() {
	*x = LocalExtensibilityOperationResponse{}
	mi := &file_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExtensibilityOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExtensibilityOperationResponse) ProtoMessage() {}

func (x *LocalExtensibilityOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExtensibilityOperationResponse.ProtoReflect.Descriptor instead.
func (*LocalExtensibilityOperationResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *LocalExtensibilityOperationResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *LocalExtensibilityOperationResponse) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the resource.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The API version of the resource.
	ApiVersion *string `protobuf:"bytes,2,opt,name=apiVersion,proto3,oneof" json:"apiVersion,omitempty"`
	// An object comprising key properties that, when paired with the resource's type and configuration, uniquely identify a resource.
	// These properties are generally a subset of the resource properties provided in the createOrUpdate request payload.
	// Formatted as a serialized JSON string.
	Identifiers string `protobuf:"bytes,3,opt,name=identifiers,proto3" json:"identifiers,omitempty"`
	// The properties of the resource.
	// Formatted as a serialized JSON string.
	Properties string `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	// Indicates the provisioning status of the resource or long-running operation.
	// There are three terminal status: Succeeded, Failed, and Canceled.
	// A null or undefined status property is treated as Succeeded.
	// Any other status is a non-terminal state and is defined by each extension (e.g., Running).
	Status        *string `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

func (x *Resource) GetIdentifiers() string {
	if x != nil {
		return x.Identifiers
	}
	return ""
}

func (x *Resource) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

func (x *Resource) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ErrorData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error details.
	Error         *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorData) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A short unlocalized string which can be used to identify a particular class of error. The code should be Pascal-cased.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// An absolute JSON Pointer (see RFC 6901) to the property causing the error.
	Target *string `protobuf:"bytes,2,opt,name=target,proto3,oneof" json:"target,omitempty"`
	// Describes the error in detail and provides debugging information.
	// If the Accept-Language header is set in the request, it must be localized accordingly.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// An array of details about specific errors that led to this reported error.
	Details []*ErrorDetail `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	// An object containing more specific information than the current object about the error.
	InnerError    *string `protobuf:"bytes,5,opt,name=innerError,proto3,oneof" json:"innerError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetInnerError() string {
	if x != nil && x.InnerError != nil {
		return *x.InnerError
	}
	return ""
}

type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A short unlocalized string which can be used to identify a particular class of error. The code should be Pascal-cased.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// An absolute JSON Pointer (see RFC 6901) to the property causing the error.
	Target *string `protobuf:"bytes,2,opt,name=target,proto3,oneof" json:"target,omitempty"`
	// Describes the error in detail and provides debugging information.
	// If the Accept-Language header is set in the request, it must be localized accordingly.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TypeFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the main index file for type definitions.
	IndexFile string `protobuf:"bytes,1,opt,name=indexFile,proto3" json:"indexFile,omitempty"`
	// Map of file paths to their contents (all type definition files).
	TypeFiles     map[string]string `protobuf:"bytes,2,rep,name=typeFiles,proto3" json:"typeFiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeFilesResponse) Reset() {
	*x = TypeFilesResponse{}
	mi := &file_extension_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeFilesResponse) ProtoMessage() {}

func (x *TypeFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeFilesResponse.ProtoReflect.Descriptor instead.
func (*TypeFilesResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{8}
}

func (x *TypeFilesResponse) GetIndexFile() string {
	if x != nil {
		return x.IndexFile
	}
	return ""
}

func (x *TypeFilesResponse) GetTypeFiles() map[string]string {
	if x != nil {
		return x.TypeFiles
	}
	return nil
}

var File_extension_proto protoreflect.FileDescriptor

const file_extension_proto_rawDesc = "" +
	"\n" +
	"\x0fextension.proto\x12\textension\"\a\n" +
	"\x05Empty\"\xa7\x01\n" +
	"\x15ResourceSpecification\x12\x1b\n" +
	"\x06config\x18\x01 \x01(\tH\x00R\x06config\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\n" +
	"apiVersion\x18\x03 \x01(\tH\x01R\n" +
	"apiVersion\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"properties\x18\x04 \x01(\tR\n" +
	"propertiesB\t\n" +
	"\a_configB\r\n" +
	"\v_apiVersion\"\xa5\x01\n" +
	"\x11ResourceReference\x12 \n" +
	"\videntifiers\x18\x01 \x01(\tR\videntifiers\x12\x1b\n" +
	"\x06config\x18\x02 \x01(\tH\x00R\x06config\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12#\n" +
	"\n" +
	"apiVersion\x18\x04 \x01(\tH\x01R\n" +
	"apiVersion\x88\x01\x01B\t\n" +
	"\a_configB\r\n" +
	"\v_apiVersion\"\xaf\x01\n" +
	"#LocalExtensibilityOperationResponse\x124\n" +
	"\bresource\x18\x01 \x01(\v2\x13.extension.ResourceH\x00R\bresource\x88\x01\x01\x127\n" +
	"\terrorData\x18\x02 \x01(\v2\x14.extension.ErrorDataH\x01R\terrorData\x88\x01\x01B\v\n" +
	"\t_resourceB\f\n" +
	"\n" +
	"_errorData\"\xbc\x01\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tH\x00R\n" +
	"apiVersion\x88\x01\x01\x12 \n" +
	"\videntifiers\x18\x03 \x01(\tR\videntifiers\x12\x1e\n" +
	"\n" +
	"properties\x18\x04 \x01(\tR\n" +
	"properties\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x01R\x06status\x88\x01\x01B\r\n" +
	"\v_apiVersionB\t\n" +
	"\a_status\"3\n" +
	"\tErrorData\x12&\n" +
	"\x05error\x18\x01 \x01(\v2\x10.extension.ErrorR\x05error\"\xc3\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\x06target\x18\x02 \x01(\tH\x00R\x06target\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x120\n" +
	"\adetails\x18\x04 \x03(\v2\x16.extension.ErrorDetailR\adetails\x12#\n" +
	"\n" +
	"innerError\x18\x05 \x01(\tH\x01R\n" +
	"innerError\x88\x01\x01B\t\n" +
	"\a_targetB\r\n" +
	"\v_innerError\"c\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\x06target\x18\x02 \x01(\tH\x00R\x06target\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\t\n" +
	"\a_target\"\xba\x01\n" +
	"\x11TypeFilesResponse\x12\x1c\n" +
	"\tindexFile\x18\x01 \x01(\tR\tindexFile\x12I\n" +
	"\ttypeFiles\x18\x02 \x03(\v2+.extension.TypeFilesResponse.TypeFilesEntryR\ttypeFiles\x1a<\n" +
	"\x0eTypeFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xea\x03\n" +
	"\x0eBicepExtension\x12b\n" +
	"\x0eCreateOrUpdate\x12 .extension.ResourceSpecification\x1a..extension.LocalExtensibilityOperationResponse\x12[\n" +
	"\aPreview\x12 .extension.ResourceSpecification\x1a..extension.LocalExtensibilityOperationResponse\x12S\n" +
	"\x03Get\x12\x1c.extension.ResourceReference\x1a..extension.LocalExtensibilityOperationResponse\x12V\n" +
	"\x06Delete\x12\x1c.extension.ResourceReference\x1a..extension.LocalExtensibilityOperationResponse\x12>\n" +
	"\fGetTypeFiles\x12\x10.extension.Empty\x1a\x1c.extension.TypeFilesResponse\x12*\n" +
	"\x04Ping\x12\x10.extension.Empty\x1a\x10.extension.EmptyB\x12\xaa\x02\x0fBicep.Local.Rpcb\x06proto3"

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData []byte
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)))
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_extension_proto_goTypes = []any{
	(*Empty)(nil),                               // 0: extension.Empty
	(*ResourceSpecification)(nil),               // 1: extension.ResourceSpecification
	(*ResourceReference)(nil),                   // 2: extension.ResourceReference
	(*LocalExtensibilityOperationResponse)(nil), // 3: extension.LocalExtensibilityOperationResponse
	(*Resource)(nil),                            // 4: extension.Resource
	(*ErrorData)(nil),                           // 5: extension.ErrorData
	(*Error)(nil),                               // 6: extension.Error
	(*ErrorDetail)(nil),                         // 7: extension.ErrorDetail
	(*TypeFilesResponse)(nil),                   // 8: extension.TypeFilesResponse
	nil,                                         // 9: extension.TypeFilesResponse.TypeFilesEntry
}
var file_extension_proto_depIdxs = []int32{
	4,  // 0: extension.LocalExtensibilityOperationResponse.resource:type_name -> extension.Resource
	5,  // 1: extension.LocalExtensibilityOperationResponse.errorData:type_name -> extension.ErrorData
	6,  // 2: extension.ErrorData.error:type_name -> extension.Error
	7,  // 3: extension.Error.details:type_name -> extension.ErrorDetail
	9,  // 4: extension.TypeFilesResponse.typeFiles:type_name -> extension.TypeFilesResponse.TypeFilesEntry
	1,  // 5: extension.BicepExtension.CreateOrUpdate:input_type -> extension.ResourceSpecification
	1,  // 6: extension.BicepExtension.Preview:input_type -> extension.ResourceSpecification
	2,  // 7: extension.BicepExtension.Get:input_type -> extension.ResourceReference
	2,  // 8: extension.BicepExtension.Delete:input_type -> extension.ResourceReference
	0,  // 9: extension.BicepExtension.GetTypeFiles:input_type -> extension.Empty
	0,  // 10: extension.BicepExtension.Ping:input_type -> extension.Empty
	3,  // 11: extension.BicepExtension.CreateOrUpdate:output_type -> extension.LocalExtensibilityOperationResponse
	3,  // 12: extension.BicepExtension.Preview:output_type -> extension.LocalExtensibilityOperationResponse
	3,  // 13: extension.BicepExtension.Get:output_type -> extension.LocalExtensibilityOperationResponse
	3,  // 14: extension.BicepExtension.Delete:output_type -> extension.LocalExtensibilityOperationResponse
	8,  // 15: extension.BicepExtension.GetTypeFiles:output_type -> extension.TypeFilesResponse
	0,  // 16: extension.BicepExtension.Ping:output_type -> extension.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	file_extension_proto_msgTypes[1].OneofWrappers = []any{}
	file_extension_proto_msgTypes[2].OneofWrappers = []any{}
	file_extension_proto_msgTypes[3].OneofWrappers = []any{}
	file_extension_proto_msgTypes[4].OneofWrappers = []any{}
	file_extension_proto_msgTypes[6].OneofWrappers = []any{}
	file_extension_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
